### ISSUE TITLE
Adding Content-Security-Policy leads to EvalError

### ISSUE THREAD

**Issue by pkyeck** [rt2zz/redux-persist#1122]
I was using redux-persist before without any problems.
Now, after adding a Content-Security-Policy meta-tag to my CRA index.html, I get the following error when the lib tries to rehydrate the store:

```
"EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'sha256-9Auc+I2...F+dIsslNOVHrux6Faio=' 'nonce-EqN....eg==' 'nonce-e+...=='".

    at walk (https://.../static/js/2.97744994.chunk.js:1:1026756)
    at walk (https://.../static/js/2.97744994.chunk.js:1:1026332)
    at walk (https://.../static/js/2.97744994.chunk.js:1:1026332)
    at walk (https://.../static/js/2.97744994.chunk.js:1:1026332)
    at Object.parse (https://.../static/js/2.97744994.chunk.js:1:1027078)
    at https://.../static/js/main.290584f2.chunk.js:1:327195
    at Object.out (https://.../static/js/2.97744994.chunk.js:1:504673)
    at https://.../static/js/2.97744994.chunk.js:1:501083
    at Array.reduceRight (<anonymous>)
    at https://.../static/js/2.97744994.chunk.js:1:501047"
```

My CSP meta tag looks something like this:

```
<meta http-equiv="Content-Security-Policy" content="base-uri 'self'; object-src 'none'; script-src 'self' 'sha256-9Auc+I2...F+dIsslNOVHrux6Faio=' 'nonce-EqN...g==' 'nonce-e+...EDg=='; style-src 'self' 'unsafe-inline'; default-src 'none'; manifest-src 'self'; connect-src 'self'; img-src 'self'">
```

I'm also using a Transform to store data in JSONL:

```
const dataTransform = createTransform(
  (inbound) => JSONL.stringify(inbound),
  (outbound) => JSONL.parse(outbound)
);
```

Anyone else having this problem?

**Comment by pkyeck** [comment]
ok, found the culprit. `json-literal` is using `eval()`  :(
