### ISSUE TITLE
Testing with Jest & Enzyme: TypeError: Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by ghasemikasra39** [rt2zz/redux-persist#1243]
The package works perfectly fine in a **non-testing env**. However, in a **testing environment**, I am getting this error:
```
TypeError: Cannot read property 'catch' of undefined
    at writeStagedState (/Users/kasra/Documents/app/node_modules/redux-persist/lib/createPersistoid.js:98:71)
    at Timeout.processNextKey [as _onTimeout] (/Users/kasra/Documents/app/node_modules/redux-persist/lib/createPersistoid.js:87:7)
``` 

```
    "react-native": "0.62.2",
    "redux-persist": "^6.0.0"
    "redux": "^4.0.4"
    "react-redux": "^7.1.3"
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.4",
    "jest": "^26.4.2",
    "jest-enzyme": "^7.1.2",
    "jest-expo": "^38.0.2",
```

**Comment by alexbrazier** [comment]
I solved it using this mock:

```js
jest.mock('redux-persist', () => {
  const real = jest.requireActual('redux-persist');
  return {
    ...real,
    persistReducer: jest
      .fn()
      .mockImplementation((config, reducers) => reducers),
  };
});
```

It basically just bypasses redux-persist by returning the reducers directly without wrapping them in redux-persist.

You can also downgrade to `jest: 25.x.x`.

**Comment by maxb94** [comment]
I solved this by including `jest.useFakeTimers()`

**Comment by johhansantana** [comment]
@alexbrazier I tried your solution but I still get the error message, though the tests pass for some reason. I am using `"jest": "^26.6.3"` though, not sure if this has to do.

```
writePromise = storage.setItem(storageKey, serialize(stagedState)).catch(onWriteFail);
                                                                                                                  ^

TypeError: Cannot read property 'catch' of undefined
```

**Comment by johhansantana** [comment]
ok, so this seems to be an error with the API of AsyncStorage. Following https://github.com/react-native-async-storage/async-storage/issues/379#issuecomment-660478051 answer I added the mock and it works now.

**Comment by Bilal-Abdeen** [comment]
I am getting the same error:
```
C:\react\Casual_Job\casualjob\node_modules\redux-persist\lib\createPersistoid.js:98
    writePromise = storage.setItem(storageKey, serialize(stagedState)).catch(onWriteFail);
                                                                      ^

TypeError: Cannot read properties of undefined (reading 'catch')
    at writeStagedState (C:\react\Casual_Job\casualjob\node_modules\redux-persist\lib\createPersistoid.js:98:71)
    at Timeout.processNextKey [as _onTimeout] (C:\react\Casual_Job\casualjob\node_modules\redux-persist\lib\createPersistoid.js:87:7)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```
redux-persist mocking code: 
```javascript 
jest.doMock('redux-persist', () => {
  const real = jest.requireActual('redux-persist');
  return {
    ...real,
    persistReducer: jest
      .fn()
      .mockImplementation((config, reducers) => reducers),
  };
}); 

jest.mock('redux-persist/integration/react', () => ({ PersistGate: (props) => props.children, }));
```
Async-Storage Mocking: 
```javascript
// This is the contents of the file .\__mocks__\@react-native-async-storage/async-storage.js
export default from "@react-native-async-storage/async-storage/jest/async-storage-mock.js";
```

**Comment by mljlynch** [comment]
Is this issue closed?
