### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by chrisblossom** [rt2zz/redux-persist#125]
We use Sentry to track JS errors and have been getting the following error:

```
TypeError: Cannot call method 'filter' of undefined
  at cb(~/redux-persist/lib/getStoredState.js:45:0)
  at getAllKeys(~/redux-persist/lib/defaults/asyncLocalStorage.js:52:0)
  at _extends(~/redux-persist/lib/getStoredState.js:41:0)
  at call(~/redux-persist/lib/persistStore.js:44:0)
  at apply(~/timers-browserify/main.js:64:0)
  at run(~/process/browser.js:67:0)
  at apply(~/process/browser.js:37:0)
  at apply(~/raven-js/src/raven.js:265:0)
```

Breakdown by browser:
```
%	Value	Last Seen
7.14%	Android 4.1	27 minutes ago
14.29%	Chrome Mobile 33.0	2 hours ago
7.14%	Chrome Mobile 43.0	2 hours ago
28.57%	Chrome Mobile 50.0	3 hours ago
7.14%	Chrome Mobile 51.0	8 hours ago
7.14%	Chrome 41.51020	6 days ago
7.14%	Chrome Mobile 34.0	6 days ago
21.43%	Mobile Safari 9.0	15 days ago
```

Any ideas what could be causing this? Any help is appreciated.

**Comment by rt2zz** [comment]
@chrisblossom are you still seeing this? I believe this was fixed in later versions.
