### ISSUE TITLE
Jest testing: store.dispatch is not a function

### ISSUE THREAD

**Issue by mkhazov** [rt2zz/redux-persist#451]
After adding autoRehydrate enhancer and call of `persistStore(store)` persisting and rehydration of my redux store works well in the app, but my unit tests started to fail with:
```
/project_path/node_modules/redux-persist/lib/persistStore.js:55
          store.dispatch(rehydrateAction(restoredState, err));
                ^

TypeError: store.dispatch is not a function
    at /project_path/node_modules/redux-persist/lib/persistStore.js:55:17
    at complete (/project_path/node_modules/redux-persist/lib/getStoredState.js:73:5)
    at /project_path/node_modules/redux-persist/lib/getStoredState.js:47:29
    at Immediate._onImmediate (/project_path/node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:18:19)
    at runCallback (timers.js:802:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
error Command failed with exit code 1.
```

**Comment by rt2zz** [comment]
you might be doing something like 
```js
//bad
const store = persistStore(createStore(...))

//good
const store = createStore(...)
const persistor = persistStore(store)
```

Short of that, it might be some bad mocks?

**Comment by khoaanh2212** [comment]
same problem and @rt2zz can not solve it

**Comment by rt2zz** [comment]
can you post your failing test here, there might be something wrong with the setup

**Comment by khoaanh2212** [comment]
this is my code on store.js
```javascript
/**
 * Create the store with asynchronously loaded reducers
 */

import { createStore, applyMiddleware, compose } from 'redux';
import { fromJS } from 'immutable';
import { routerMiddleware } from 'react-router-redux';
import createSagaMiddleware from 'redux-saga';
import { persistStore, autoRehydrate } from 'redux-persist-immutable';
import createReducer from './reducers';

const sagaMiddleware = createSagaMiddleware();

export default function configureStore(initialState = {}, history) {
  // Create the store with two middlewares
  // 1. sagaMiddleware: Makes redux-sagas work
  // 2. routerMiddleware: Syncs the location/URL path to the state
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
  ];

  const enhancers = [
    applyMiddleware(...middlewares),
  ];

  // If Redux DevTools Extension is installed use it, otherwise use Redux compose
  /* eslint-disable no-underscore-dangle */
  const composeEnhancers =
    process.env.NODE_ENV !== 'production' &&
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ : compose;
  /* eslint-enable */

  const store = createStore(
    createReducer(),
    fromJS(initialState),
    composeEnhancers(...enhancers, autoRehydrate())
  );

  // Extensions
  store.runSaga = sagaMiddleware.run;
  store.asyncReducers = {}; // Async reducer registry

  persistStore(store, { whitelist: ['global', 'language'] });

  // Make reducers hot reloadable, see http://mxs.is/googmo
  /* istanbul ignore next */
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      import('./reducers').then((reducerModule) => {
        const createReducers = reducerModule.default;
        const nextReducers = createReducers(store.asyncReducers);

        store.replaceReducer(nextReducers);
      });
    });
  }

  return store;
}

```

**Comment by vesteinn** [comment]
Ran into the same issue when imports were not fixed, i.e. should have been `import {store }` instead of` import store` after also exporting a persistor in my file.

**Comment by sospedra** [comment]
That's usually a problem with `redux-mock-store`

Remember that:

`import configureStore from 'redux-mock-store'`

`configureStore` does **not** return a valid store, but a factory
 
Meaning that you have to call the factory to get the store:

`const store = configureStore([])()`
