### ISSUE TITLE
[v5]: ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by clodal** [rt2zz/redux-persist#465]
Hi there, on version: `"redux-persist": "^5.0.0-beta.14"`, if i do: `import storage from 'redux-persist/lib/storage'`, webpack throws the following error `ReferenceError: regeneratorRuntime is not defined`. Is this related to the this package or is it my webpack config? Thanks!

Details as follow:
```
webpack: Compiling...


redux-persist failed to create sync storage. falling back to memory storage.
/user/client/node_modules/redux-persist/lib/storage/createWebStorage.js:20
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(key) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /user/client/node_modules/redux-persist/lib/storage/createWebStorage.js:20:50
    at createWebStorage (/user/client/node_modules/redux-persist/lib/storage/createWebStorage.js:40:6)
    at Object.<anonymous> (/user/client/node_modules/redux-persist/lib/storage/index.js:11:50)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by clodal** [comment]
Sorry found out this was a SSR issue, will check my config.

**Comment by clodal** [comment]
I fix this issue, following the answer provided in this [Stackoverflow question](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined)

**Comment by rt2zz** [comment]
Thanks for bringing this up. async usage was removed in 5.0.0-rc.1 in favor of simple promises 👍  so polyfill should no longer be required.

**Comment by clodal** [comment]
@rt2zz Nice, already one step ahead!
