### ISSUE TITLE
SSR side errors

### ISSUE THREAD

**Issue by veeramarni** [rt2zz/redux-persist#553]
How to make it isomorphic, so it won't fail when doing SSR?

Config
--
import { persistCombineReducers } from 'redux-persist';
import storage from 'redux-persist/es/storage';

const config = {
    key: 'root', // key is required
    storage, // storage is now required
}

/**
 * Add any reducers required for this app dirctly in to
 * `combineReducers`
 */
const createReduxStore = (initialState, client: ApolloClient) => {
    const store: Store<any> =
        createStore<any>(
            persistCombineReducers(config, {
                ...reducers,
                theme: themeReducer,
            }),
            {} as StoreState.XtermStack,
            composeEnhancers(...enhancers(client.middleware())),
        );
    return store;
};

export { createReduxStore };

Error
--
```
(function (exports, require, module, __filename, __dirname) { import createWebStorage from './createWebStorage';
                                                                                                             ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)

```

**Comment by rt2zz** [comment]
looks like you do not support es6 modules on your server, in which case you should import out of lib instead of es

Also you probably do not want to use persist during SSR unless you are using cookie storage.

**Comment by veeramarni** [comment]
I was able to get rid of that error after using `lib`
Is there anything additional step I need to take care to run as SSR. I'm not expecting to save anything in `redux-persist` until the app opens in the browser. Or by leaving as it is won't harm anything?
