### ISSUE TITLE
SyntaxError: Unexpected token import with Jest

### ISSUE THREAD

**Issue by ahmad2smile** [rt2zz/redux-persist#643]
I'm trying to setup a jest snapshot test with redux-persist in my react-native project. I don't think it an es2015 imports problem as my test code looks something like this:

    import React from "react"

    import "react-native"

    // Note: test renderer must be required after react-native.

    import renderer from "react-test-renderer"

    import App from "../App"

    it("renders correctly", () => {
	const app = renderer.create(<App />).toJSON()
	expect(app).toMatchSnapshot()

    })

    

I ran this exact same test before I added `redux-persist` and it was working. 

Error thrown by jest:

● Test suite failed to run

    /Users/a_050313/Documents/dev/scheduling/node_modules/redux-persist/es/integration/react.js:9
    import React, { PureComponent } from 'react'; // eslint-disable-line import/no-unresolved
    ^^^^^^
    
    SyntaxError: Unexpected token import

      1 | import React, { Component } from "react"
      2 | import { Provider } from "react-redux"
    > 3 | import { PersistGate } from "redux-persist/es/integration/react"
      4 | 
      5 | import "./__debug__/ReactotronConfig" // Run Reactron Tools config
      6 | 
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (App.js:3:13)
      at Object.<anonymous> (__tests__/App.js:7:10)`

**Comment by ahmad2smile** [comment]
The solution by official docs [here](https://stackoverflow.com/questions/48056631/syntaxerror-unexpected-token-import-with-jest/48056912#48056912)
